name: Deploy Fake
on:
    workflow_call:
        inputs:
            ambiente:
                type: string
                default: "desenvolvimento"
                required: true
                description: "Ambiente onde vai ser feito o deploy"
jobs:
    CD:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de ${{ secrets.ambiente }}"