name: Deploy Fake
on:
    workflow_dispatch:
jobs:
    CD:
        runs-on: ubuntu-latest
        environment: homologacao
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de ${{ vars.AMBIENTE_DEPLOY }}"