name: Deploy Fake
on:
    repository_dispatch:
        types:
        - deploy-remoto
jobs:
    CD:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy no ambiente
              run: echo "Executando o deploy no ambiente de ${{ github.event.client_payload.ambiente }}"